# Configuration for SPX Day Time
spx_day_time_config:
  early_close_days:
    - "2023-07-03"  # Independence Day 2023
    - "2023-11-24"  # Thanksgiving Day 2023 (day after)
    - "2024-07-03"  # Independence Day 2024
    - "2024-11-29"  # Thanksgiving Day 2024 (day after)
    - "2024-12-24"  # Christmas Eve 2024
    - "2025-07-03"  # Independence Day 2025
    - "2025-11-28"  # Thanksgiving Day 2025 (day after)
    - "2025-12-24"  # Christmas Eve 2025
  special_holidays:
    - "2025-01-09"  # National Day of Mourning for Jimmy Carter
  valid_times:
    - "09:33"
    - "09:45"
    - "10:00"
    - "10:15"
    - "10:30"
    - "10:45"
    - "11:00"
    - "11:15"
    - "11:30"
    - "11:45"
    - "12:00"
    - "12:15"
    - "12:30"
    - "12:45"
    - "13:00"
    - "13:15"
    - "13:30"
    - "13:45"
    - "14:00"
    - "14:15"
    - "14:30"
    - "14:45"
    - "15:00"
    - "15:15"
    - "15:30"
    - "15:45"
